#!/usr/bin/env bash
echo "INICIANDO"
printf "\n\033[0;44m---> Starting the SSH server.\033[0m\n"
echo "PUBLIC IP"
curl ipinfo.io/ip
echo "STORAGE"
cd /app/server/bin/
echo "Memoria Java: $MEMORYSIZE"
echo "file system:"
df -h
/app/java/bin/java -jar server-0.0.1.jar
